# Generated by Django 3.2.3 on 2021-05-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name': 'Victim', 'verbose_name_plural': 'Victims'},
        ),
        migrations.RenameField(
            model_name='facebook',
            old_name='user_name',
            new_name='email',
        ),
    ]
